---
- hosts: all
  vars:
    home: /Users/{{ ansible_user_id }}
  tasks:
  - name: Tap the homebrew taps
    homebrew_tap: tap={{ item }}
    with_items:
      - caskroom/cask
      - homebrew/science
      - mindriot101/alt
      - homebrew/headonly
      - homebrew/dupes

  - name: Install homebrew packages
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - vim
      - zsh
      - htop-osx
      - gcc
      - ctags
      - tree
      - graphviz
      - tmux
      - md5sha1sum
      - coreutils
      - freetype
      - watch
      - the_silver_searcher
      - wget
      - gawk
      - dos2unix
      - ssh-copy-id
      - nmap
      - ffmpeg
      - imagemagick
      - trash
      - hdf5
      - sextractor
      - par
      - gpg2

      # Docker
      - boot2docker
      - docker

      # Databases
      - postgresql
      - mariadb
      - redis

      # Ruby related
      - chruby
      - ruby-install
      - direnv

      # Exotic languages
      - erlang
      - elixir
      - ghc
      - cabal-install
      - leiningen

      # Javascript
      - node
      
      # Science
      - cfitsio
      - wcslib
      - montage
      - wcstools

      # My stuff
      - ds9

      # Head only recipes
      - git-hg

      - grep

  - name: Install casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - vlc
      - virtualbox
      - vagrant
      - caffeine
      - xquartz
      - mendeley-desktop
      - x2goclient
      - fluid
      - skim
      - usb-overdrive
      - reaper
      - dropbox
      - limechat
      - adium
      - libreoffice
      - skype
      - firefox
      - google-chrome
      - thunderbird
      - gimp
      - steam
      - spectacle
      - flux

