---
homebrew_taps:
- caskroom/cask
- caskroom/fonts
- homebrew/science
- mindriot101/alt
- homebrew/headonly
- homebrew/dupes
- universal-ctags/universal-ctags
- homebrew/services
- homebrew/completions

homebrew_packages:
- ansible
- binutils
- cargo-completion
- clang-format
- coreutils
- dos2unix
- editorconfig
- exercism
- fabric
- ffmpeg
- gawk
- gcc
- git
- git-lfs
- gnu-sed
- graphviz
- htop
- imagemagick
- irssi
- jq
- keybase
- md5sha1sum
- multitail
- mutt
- ncdu
- ngircd
- nmap
- offlineimap
- openssh
- pandoc
- par
- parallel
- pdsh
- reattach-to-user-namespace
- rlwrap
- ssh-copy-id
- tclap
- the_silver_searcher
- tmux
- trash
- tree
- urlview
- vim
- w3m
- watch
- weechat
- wget
- youtube-dl
- zsh

# Docker
- docker
- docker-machine
- docker-compose

# Databases
- postgresql
- mariadb
- redis

# Exotic languages
- erlang
- elixir
- leiningen
- nim
- haskell-stack

# Javascript
- node

# Astronomy
- wcslib
- wcstools
- montage
- sextractor

# My stuff
- ds9


homebrew_casks:
- dropbox
- firefoxnightly
- gimp
- google-chrome
- gpgtools
- iterm2
- jadengeller-helium
- keybase
- keyboard-cleaner
- limechat
- mactex
- macvim
- mendeley-desktop
- messenger
- omnidisksweeper
- saoimage-ds9
- skim
- skype
- spectacle
- spotify
- steam
- transmission
- vagrant
- virtualbox
- vlc
- whatsapp
- wireshark
- zoomus

# Fonts
- font-inconsolata
- font-inconsolata-dz

npm_packages:
- react-native-cli
- nativefier
- brunch

homebrew_services:
- mariadb
- postgresql
- nginx
- redis

pip_packages:
- "git+https://github.com/mindriot101/pip-available-versions#egg=pip_available_versions"
