---
- name: Get pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_dir }}"
    force: yes

- name: Get pyenv plugins
  git:
    repo: "https://github.com/yyuu/pyenv-{{ item }}.git"
    dest: "{{ pyenv_dir }}/plugins/pyenv-{{ item }}"
    force: yes
  with_items: "{{ pyenv_plugins }}"

- name: Link custom ngts python version into versions dir
  file:
    src: /usr/local/python
    dest: "{{ pyenv_dir }}/versions/ngts"
    state: link
  when: ansible_hostname == "ngtshead"
