---
- name: Get pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_dir }}"
    force: yes

- name: Get pyenv plugins
  git:
    repo: "https://github.com/yyuu/pyenv-{{ item }}.git"
    dest: "{{ pyenv_dir }}/plugins/pyenv-{{ item }}"
    force: yes
  with_items: "{{ pyenv_plugins }}"

- name: Install python versions
  shell: "PYTHON_CONFIGURE_OPTS=--enable-unicode=ucs2 PIP_INDEX_URL= {{ pyenv_dir }}/bin/pyenv install {{ item }} creates={{ pyenv_dir }}/versions/{{ item }}"
  with_items:
    - miniconda3-latest
    - pypy-5.1
    - 2.6.9
    - 2.7.11
    - 3.3.6
    - 3.4.4
    - 3.5.1
  ignore_errors: yes

- name: Link custom ngts python version into versions dir
  file:
    src: /usr/local/python
    dest: "{{ pyenv_dir }}/versions/ngts"
    state: link
  when: ansible_hostname == "ngtshead"
