- name: Tap the homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items: homebrew_packages

- name: Install cfitsio with examples
  homebrew: name=cfitsio install_options=with-examples

- name: Install vim with arguments
  homebrew: name=vim state=latest install_options=override-system-vi

- name: Install neovim head
  homebrew: name=neovim state=head

- name: Install universal ctags head
  homebrew: name=universal-ctags state=head

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  with_items: homebrew_casks

- name: Update some iTerm2 defaults
  command: defaults write com.googlecode.iterm2 {{ item }}
  with_items:
    - OpenFileInNewWindows -bool true
    - PinchToChangeFontSizeDisabled -bool true
    - UseUnevenTabs -bool false

- name: Ensure sudoers file is valid
  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults tty_tickets"
    validate='visudo -cf %s' insertafter='Defaultsenv_keep += "HOME MAIL"'
    line="Defaults tty_tickets"
  become: yes
