- name: Tap the homebrew taps
  homebrew_tap: tap={{ item }} state=present
  tags:
    - packaging
  with_items: "{{ homebrew_taps }}"

- name: Install homebrew packages
  homebrew: name={{ item }} state=latest
  tags:
    - packaging
  with_items: "{{ homebrew_packages }}"

- name: Link service items
  file:
    src: /usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist
    path: "{{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist"
    state: link
    force: yes
  tags:
    - packaging
  with_items: "{{ homebrew_services }}"

- name: Start services at launch
  command: launchctl load -w {{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
  tags:
    - packaging
  with_items: "{{ homebrew_services }}"

- name: Install cfitsio with examples
  homebrew: name=cfitsio install_options=with-examples
  tags:
    - packaging

- name: Install vim with arguments
  homebrew: name=vim state=latest install_options=override-system-vi
  tags:
    - packaging

- name: Install gnuplot with arguments
  homebrew: name=gnuplot state=latest install_options=with-x11,with-cairo,with-wxmac,with-aquaterm
  tags:
    - packaging

- name: Install emacs with arguments
  homebrew: name=emacs state=latest install_options=with-cocoa,with-imagemagick
  tags:
    - packaging

- name: Install universal ctags head
  homebrew: name=universal-ctags state=head
  tags:
    - packaging

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  tags:
    - packaging
  with_items: "{{ homebrew_casks }}"

- name: Install npm packages
  npm: name={{ item }} global=yes production=yes state=latest
  tags:
    - packaging
  with_items: "{{ npm_packages }}"

- name: Update some iTerm2 defaults
  command: defaults write com.googlecode.iterm2 {{ item }}
  with_items:
    - OpenFileInNewWindows -bool true
    - PinchToChangeFontSizeDisabled -bool true
    - UseUnevenTabs -bool false

- name: Ensure sudoers file is valid
  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults tty_tickets"
    validate='visudo -cf %s' insertafter='Defaultsenv_keep += "HOME MAIL"'
    line="Defaults tty_tickets"
  become: yes

- name: Copy sshd template
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r
  become: yes
